remote_theme: just-the-docs/just-the-docs
baseurl: "/atn-review-policy"
title: "Review Policy for Thunderbird Add-ons"
logo: "/assets/logo.png"
logo_only: true

url: "https://thunderbird.github.io/atn-review-policy/"
color_scheme: light

include:
  - assets

# Navigation
nav_external_links:
  - title: "addons.thunderbird.net"
    url: "https://addons.thunderbird.net"
  - title: "Mozilla's Conditions of Use"
    url: "https://www.mozilla.org/about/legal/acceptable-use/"
  - title: "Mozilla's Source Code Submission guidelines"
    url: "https://extensionworkshop.com/documentation/publish/source-code-submission/"
  - title: "Mozilla's third party library guidelines"
    url: "https://extensionworkshop.com/documentation/publish/third-party-library-usage/"
  - title: "Mozilla's Lean Data Practices"
    url: "https://foundation.mozilla.org/en/lean-data-practices/"
  - title: "Mozilla's Data Privacy Principles"
    url: "https://www.mozilla.org/en-US/privacy/principles/"
  - title: "Thunderbird Add-on Reviewer Guide"
    url: "https://addons-reviewer-guide.thunderbird.net/"

# Define look of right-side TOC
just_the_docs:
  search_enabled: true
